#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: A pursuit of truth

# Short bio or description (displayed in the header)
description: This is a collection of random thoughts and mathematical endevours in my pursuit of the "truth" which most likely will never end.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/4715779?v=3&s=460

#
# Flags below are optional
#

# markdown: maruku

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: micke.green@gmail.com
  facebook: SolusEtUnicus
  flickr:
  github: DoktorMike
  instagram:
  linkedin: mickegreen
  pinterest:
  rss: Anything # just type anything here for a working RSS icon
  twitter: Doktor_Mike
  stackoverflow: /users/889814/dr-mike # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +MichaelGreenSolosEtUnicus


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: doktormike

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-88816710-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://doktormike.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /blog/:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  #syntax_highlighter: rouge
  #syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    #css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dr. Michael Green"
resume_title:                   "Artificial Intelligence Evangelist"
resume_contact_email:           "micke.green@gmail.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "http://doktormike.github.io/cv"
  resume_twitter_url:           "http://twitter.com/Doktor_Mike"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/SolusEtUnicus"
  resume_linkedin_url:          "https://www.linkedin.com/in/mickegreen"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://modeling.green"

# Design settings
resume_theme:                   default
